name: Build & Test Packages - Nix - Ubuntu

on:
  merge_group:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_test_packages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distro:
          - humble
          - jazzy
          - kilted
          - rolling
    env:
      ROS_DISTRO: ${{ matrix.ros_distro }}
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: cachix/install-nix-action@v31.10.4
        with:
          extra_nix_config: |
            accept-flake-config = true

      - uses: cachix/cachix-action@v17
        with:
          name: spikonado
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and Cache Shell Environment
        run: |
          nix develop --impure --profile rfdf-shell -c true
          cachix push spikonado rfdf-shell

      - name: Build Packages
        shell: 'nix develop --profile rfdf-shell -c bash -e {0}'
        run: colcon build --event-handlers=console_cohesion+ --symlink-install

      - name: Test Packages
        shell: 'nix develop --profile rfdf-shell -c bash -e {0}'
        run: |
          colcon test --event-handlers=console_direct+
          colcon test-result --all
          colcon test-result --verbose
